// <auto-generated />
using System;
using MateoAPI.Entities.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MateoAPI.Migrations
{
    [DbContext(typeof(MateoDbContext))]
    [Migration("20250308174550_CreateTableEntrenamiento")]
    partial class CreateTableEntrenamiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("MateoAPI.Entities.Models.Entrenamiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uuid")
                        .HasColumnName("id_request");

                    b.Property<int?>("IdTipoEjercicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_ejercicio");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<short?>("Repeticiones")
                        .HasColumnType("smallint")
                        .HasColumnName("repeticiones");

                    b.Property<short?>("SegundosDescanso")
                        .HasColumnType("smallint")
                        .HasColumnName("segundos_descanso");

                    b.Property<short?>("SegundosEntrenamiento")
                        .HasColumnType("smallint")
                        .HasColumnName("segundos_entrenamiento");

                    b.Property<short?>("Serie")
                        .HasColumnType("smallint")
                        .HasColumnName("serie");

                    b.Property<DateTime>("Termino")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termino");

                    b.HasKey("Id");

                    b.HasIndex("IdRequest")
                        .IsUnique();

                    b.HasIndex("IdUsuario", "Inicio");

                    b.ToTable("entrenamiento", "mateo");
                });
#pragma warning restore 612, 618
        }
    }
}
